from enum import Enum


class Vertragsart(str, Enum):
    """
    AufzÃ¤hlung der Vertragsarten.
    """

    ENERGIELIEFERVERTRAG = "ENERGIELIEFERVERTRAG"
    NETZNUTZUNGSVERTRAG = "NETZNUTZUNGSVERTRAG"
    BILANZIERUNGSVERTRAG = "BILANZIERUNGSVERTRAG"
    MESSSTELLENBETRIEBSVERTRAG = "MESSSTELLENBETRIEBSVERTRAG"
    BUENDELVERTRAG = "BUENDELVERTRAG"
