import uuid as uuid_pkg
from enum import Enum

from sqlmodel import Field, Relationship
from sqlmodel._compat import SQLModelConfig


class Rechnungstyp(str, Enum):
    """
    Abbildung verschiedener Rechnungstypen zur Kennzeichnung von Rechnungen
    """

    ENDKUNDENRECHNUNG = "ENDKUNDENRECHNUNG"
    NETZNUTZUNGSRECHNUNG = "NETZNUTZUNGSRECHNUNG"
    MEHRMINDERMENGENRECHNUNG = "MEHRMINDERMENGENRECHNUNG"
    MESSSTELLENBETRIEBSRECHNUNG = "MESSSTELLENBETRIEBSRECHNUNG"
    BESCHAFFUNGSRECHNUNG = "BESCHAFFUNGSRECHNUNG"
    AUSGLEICHSENERGIERECHNUNG = "AUSGLEICHSENERGIERECHNUNG"
    TURNUSRECHNUNG = "TURNUSRECHNUNG"
    ABSCHLAGSRECHNUNG = "ABSCHLAGSRECHNUNG"
    ABSCHLUSSRECHNUNG = "ABSCHLUSSRECHNUNG"
    ZWISCHENRECHNUNG = "ZWISCHENRECHNUNG"
    INTEGRIERTE_13_TE_RECHNUNG = "INTEGRIERTE_13TE_RECHNUNG"
    MONATSRECHNUNG = "MONATSRECHNUNG"
    ZUSAETZLICHE_13_TE_RECHNUNG = "ZUSAETZLICHE_13TE_RECHNUNG"
