name: "BO4E Consistency Check"

on: [push]
jobs:
  bo4e_consistency_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: uv sync --group generate_bo4e --group formatting
      - name: Load BO4E version
        run: cat bo4e/tox.env >> "$GITHUB_ENV"
      - name: Build BO4E
        run: |
          uv run --group generate_bo4e bost -o "tmp/bo4e_schemas" -t "$BO4E_VERSION" -c "bo4e/bo4e_config.json" --clear-output --cache-dir "tmp/bo4e_cache"
          uv run --group generate_bo4e bo4e-generator -i "tmp/bo4e_schemas" -o "src/ibims/bo4e" --clear-output -t "$BO4E_VERSION"
      - name: Run formatters
        run: |
          uv run --group formatting isort src/ibims/bo4e
          uv run --group formatting black src/ibims/bo4e
      - name: Detect changed files
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: src/ibims/bo4e
      - name: Fail if changes detected
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "src/ibims/bo4e is inconsistent with the configuration in bo4e/. \
          Please regenerate the models (see README / bo4e_consistency.yml) and commit the changes or try editing the configuration files \
          if you want to change files in src/ibims/bo4e/."

          echo "The following files have been changed:"
          echo "${{ steps.verify-changed-files.outputs.changed_files }}"
          git diff
          exit 1
