name: "Test Doc Creation (Sphinx)"
on: [push]
jobs:
  docbuild:
    name: Check Docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"] # todo: bump to 3.12 when possible; https://github.com/Hochfrequenz/intermediate-bo4e-migration-models/issues/48
        os: [ubuntu-latest]
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group docs
      - name: Check Docs
        run: |
          uv run --group docs sphinx-build -b html -d ${{ runner.temp }}/doctrees docs ${{ runner.temp }}/html
          uv run --group docs sphinx-build -n -T -b doctest -d ${{ runner.temp }}/doctrees docs docs/_build/html
          uv run --group docs python -m doctest README.md
